apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGOHOST: "service-mongodb" # This matches the Service name from your mongo-db.yml
  MONGOPORT: "27017"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: saadazeem786/testapp:latest5
          imagePullPolicy: IfNotPresent # <--- ADD THIS LINE
          command: ["node"]
          args: ["index.js"]
          env:
            - name: MONGOHOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGOHOST
            - name: MONGOPORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGOPORT
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-app # This MUST match the Deployment label exactly
  ports:
    - name: http
      port: 3000
      targetPort: 3000